services:
  database:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ledgerarq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: America/Recife
    ports:
      - 5450:5432
    volumes:
      - /usr/share/zoneinfo/America/Recife:/etc/localtime:ro
      - dbdata:/var/lib/postgresql/data
    restart: 'unless-stopped'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  dbdata:
    name: database-data
  pgadmin-data:
